[package]
name = "tardis-example-mq"
version = "0.1.0"
authors = ["gudaoxuri"]
edition = "2021"

[dependencies]
tardis = { path = "../..", features = ["mq", "test"] }
# Example only
testcontainers = { version = "^0.13" }



