[package]
name = "tardis"
version = "0.1.0-alpha5"
authors = ["gudaoxuri <i@sunisle.org>"]
description = "Elegant, clean Rust development framework"
keywords = ["http", "database", "web", "redis", "mq"]
categories = [
    "asynchronous",
    "web-programming",
    "database",
    "caching",
]
homepage = "https://tardis.idealworld.group"
documentation = "https://tardis.idealworld.group"
repository = "https://github.com/ideal-world/tardis"
license = "MIT"
edition = "2021"
readme = "README.md"

[profile.release]
lto = true
codegen-units = 1

[lib]
name = "tardis"
path = "src/lib.rs"

[features]
default = ["trace", "rt_tokio"]
trace = ["tracing", "tracing-subscriber"]
crypto = ["rust-crypto", "rsa", "pkcs8", "gmsm", "num"]
rt_tokio = ["tokio"]
future = ["rt_tokio", "futures", "async-stream", "futures-util", "async-trait"]
reldb = ["future", "sqlparser", "sea-orm", "sea-query"]
web-server = ["trace", "future", "poem", "poem-openapi", "poem-openapi-derive"]
web-client = ["rt_tokio", "reqwest"]
cache = ["redis"]
mq = ["futures-util", "lapin", "amq-protocol-types", "async-global-executor"]
test = ["testcontainers"]

[dependencies]
# Basic
serde = { version = "^1", features = ["derive"] }
serde_json = { version = "^1" }
derive_more = { version = "^0" }
uuid = { version = "^0", features = ["serde", "v4"] }
base64 = { version = "^0" }
hex = { version = "^0" }
lazy_static = { version = "^1" }
log = { version = "^0" }
rand = { version = "^0.8" }
rand_core = { version = "^0.6" }
chrono = { version = "^0.4" }
env_logger = { version = "^0" }
config = { version = "^0" }
regex = { version = "^1" }
url = { version = "^2" }

# Tokio
tokio = { version = "^1.17", features = ["macros", "rt-multi-thread", "signal"], optional = true }

# Crypto
rust-crypto = { version = "^0", optional = true }
rsa = { version = "^0", optional = true }
pkcs8 = { version = "^0.7", optional = true }
gmsm = { version = "^0", optional = true }
num = { version = "^0", optional = true }

# Future
futures = { version = "^0.3", optional = true }
async-stream = { version = "^0.3", optional = true }
futures-util = { version = "^0.3", optional = true }
async-trait = { version = "^0", optional = true }

# Tracing
tracing = { version = "^0.1", optional = true }
tracing-subscriber = { version = "^0.3", features = ["env-filter"], optional = true }

# RelDB
sea-orm = { version = "^0.6", features = ["sqlx-all", "macros", "runtime-tokio-rustls", "debug-print"], optional = true }
sea-query = { version = "^0.21", optional = true }
sqlparser = { version = "^0.14", optional = true }

# Web Server
poem-openapi = { version = "^1.3", features = ["rapidoc", "chrono"], optional = true }
poem-openapi-derive = { version = "^1.3", optional = true }
poem = { version = "^1.3", features = ["csrf", "opentelemetry", "rustls", "prometheus", "websocket"], optional = true }

# Web Client
reqwest = { version = "^0.11", features = ["json"], optional = true }

# Redis
redis = { version = "^0.21", features = ["tokio-comp"], optional = true }

# Rabbit
lapin = { version = "^2.0", optional = true }
amq-protocol-types = { version = "^7", optional = true }
async-global-executor = { version = "^2", optional = true }

# Test
testcontainers = { version = "^0", optional = true }

[dev-dependencies]
# Common
tokio = { version = "^1", features = ["time", "rt", "macros"] }
criterion = { version = "0.3" }

[[test]]
name = "test_basic_crypto"
required-features = ["crypto"]

[[test]]
name = "test_reldb_client"
required-features = ["test", "reldb"]

[[test]]
name = "test_web_server"
required-features = ["test", "web-server", "cache", "web-client"]

[[test]]
name = "test_web_client"
required-features = ["test", "web-client"]

[[test]]
name = "test_cache_client"
required-features = ["test", "cache"]

[[test]]
name = "test_mq_client"
required-features = ["test", "mq"]

[[bench]]
name = "json_benchmark"
harness = false

[[bench]]
name = "field_benchmark"
harness = false

[[bench]]
name = "crypto_benchmark"
harness = false
required-features = ["crypto"]