[csm.doc]
content_max_len = 100
[csm.tag]
name_max_len = 4

[fw.app]
id = "multi-apps"
name = "多应用聚合示例"
desc = ""
version = "1.0.0"

[fw.web_server]
port = 8089
[[fw.web_server.modules]]
code = "doc"
title = "文档应用示例"
doc_urls = [["test env", "http://localhost:8089/"]]
[[fw.web_server.modules]]
code = "tag"
title = "标签应用示例"
doc_urls = [["test env", "http://localhost:8089/"]]

[fw.db]
url = "mysql://root:123456@localhost:3306/test"
[fw.db.modules.tag]
#
url = "mysql://root:123456@localhost:3306/test"