[package]
name = "tardis-example-perf-test"
version = "0.1.0"
authors = ["gudaoxuri"]
edition = "2021"
publish = false

[dependencies]
# Tardis Functions
tardis = { path = "../..", features = ["web-server", "reldb"] }