[package]
name = "macros_examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tardis = { path = "../../tardis", features = ["reldb-postgres"] }