on:
  workflow_run:
    workflows: ["CHECK"]
    types: ["completed"]
    tags:
      - '*'

name: RELEASE

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo login
        run: cargo login ${{ secrets.CRATES_TOKEN }}
      - name: cargo package
        run: cargo package
      - name: cargo publish
        run: cargo publish
